#!/bin/sh

ssh root@10.14.14.5 /etc/mysc/jost/camera3

rm /temp/camera3.tar

scp root@10.14.14.5:/temp/camera3.tar /temp/camera3.tar

cd /temp

rm -R /video/camera3/*

tar xvf camera3.tar -C /video

cd /video/camera3

cp /etc/mysc/rename /video/camera3/rename

/video/camera3/rename

dat=`date -d "yesterday" +%Y-%m-%d`

ffmpeg -r 10 -i %06d.jpg -r 10 -vcodec mjpeg -qscale 1  /video_done/camera3/$dat.avi

cp /video_done/camera3/$dat.avi /ya/jost/camera3/$dat.avi

