#!/usr/bin/python


import os
import datetime

ys=datetime.datetime.today()
nd=ys - datetime.timedelta(days=1)
s = str(nd)

sd = s[0:10]

ssd=sd.split('-')

yd = ssd[0]
md = ssd[1]
dd = ssd[2]
ext = '.avi'
tjost = yd+'-'+md+'-'+dd+ext
#md='07'

if md == '06':
    md='Jun'

if md == '07':
    md='Jul'

if md == '08':
    md='Aug'

tdat = yd+'-'+md+'-'+dd+ext
fpath_penta='/ya/penta/'+tdat
fpath_karg='/ya/karg/'+tdat
fpath_cam1='/ya/jost/camera1/'+tjost
fpath_cam3='/ya/jost/camera3/'+tjost

filo = open('/etc/mysc/ch_ya_res', 'w')

#---------------------------------------------------------
dat = datetime.datetime.today()
dat = str(dat)
tm = dat.split(' ')
dd = tm[0]
dt = tm[1]
ddt = dt.split('.')
ddt2 = str(ddt[0])
ddt3 = ddt2.split(':')
tt = dd + ' ' + ddt3[0] + '>' + ddt3[1] + '>' + ddt3[2]
#--------------------------------------------------------

filo.write(tt + '\n')


#----------------------------------------------------------
def ch_path(n):
    if os.path.exists(n):
	filo.write ("************************"+'\n')
	filo.write ('ok'+' ')
	filo.write(n + ' ' +(str(os.path.getsize(n)/1024) + ' Kb') + '\n')
	filo.write ("************************"+'\n')

    else:
	filo.write ("************************"+'\n')
	filo.write (('Error. Check file  ' + n) + '\n')
	filo.write ("************************"+'\n')
#----------------------------------------------------------

ch_path(fpath_penta)
ch_path(fpath_karg)
ch_path(fpath_cam1)
ch_path(fpath_cam3)

filo.close()


os.system("/bin/cat /etc/mysc/ch_ya_res | /usr/sbin/ssmtp n.v.shadrin@gmail.com")
